### ISSUE TITLE
Could this package possible work in combination with `deno compile`

### ISSUE THREAD

**Issue by danielr1996** [ayoreis/import#1]
I know the README explicetely states that it is inteded for use with deno deploy. However I was wondering if this could also be used to support dynamic imports for a `deno compile`d application, since [deno doesn't allow dynamic imports since two years after opening the issue ](https://github.com/denoland/deno/issues/8655). 

I couldn't get `importModule` to work at all, however `importString` seemed to work at first, but when I compile my application I get 
```
ERROR: [plugin: deno] Failed to call 'deno info' on 'https://denopkg.dev/gh/danielr1996/bumpup@main/packages/log/mod.ts'
    {
      detail: Error: Failed to call 'deno info' on 'https://denopkg.dev/gh/danielr1996/bumpup@main/packages/log/mod.ts'
        at Module.info (https://deno.land/x/esbuild_deno_loader@0.5.2/src/deno.ts:26:19)
        at async loadFromCLI (https://deno.land/x/esbuild_deno_loader@0.5.2/src/native_loader.ts:24:42)
        at async load (https://deno.land/x/esbuild_deno_loader@0.5.2/src/native_loader.ts:9:20)
        at async callback (https://deno.land/x/esbuild@v0.14.53/wasm.js:973:28)
        at async handleRequest (https://deno.land/x/esbuild@v0.14.53/wasm.js:701:30),
      id: "",
      location: {
        column: 18,
        file: "file:///C:/Users/danie/Documents/Entwicklung/bumpup",
        length: 68,
        line: 1,
        lineText: 'import {log} from "https://denopkg.dev/gh/danielr1996/bumpup@main/packages/log/mod.ts";',
        namespace: "",
        suggestion: ""
      },
      notes: [],
      pluginName: "deno",
      text: "Failed to call 'deno info' on 'https://denopkg.dev/gh/danielr1996/bumpup@main/packages/log/mod.ts'"
    }

```

As it seems indeed esbuild is used to compile the string instead of the dynamic data uri import. `deno info` works locally for me
```
$ deno info https://denopkg.dev/gh/danielr1996/bumpup@main/packages/log/mod.ts
local: C:\Users\danie\AppData\Local\deno\deps\https\denopkg.dev\649ed91de23002ed1a193a9522b3f0538bd7d6a726bfdb033defe48d62c502e8
emit: C:\Users\danie\AppData\Local\deno\gen\https\denopkg.dev\649ed91de23002ed1a193a9522b3f0538bd7d6a726bfdb033defe48d62c502e8.js
type: TypeScript
dependencies: 3 unique (total 1.03KB)

https://denopkg.dev/gh/danielr1996/bumpup@main/packages/log/mod.ts (53B)
└─┬ https://denopkg.dev/gh/danielr1996/bumpup@main/packages/log/src/log.ts (363B)
  └─┬ https://denopkg.dev/gh/danielr1996/bumpup@main/packages/log/deps.ts (60B)
    └── https://denopkg.dev/gh/danielr1996/bumpup@main/packages/cli/src/lib/types.ts (
```

so im unsure why this error gets thrown. 

I will look further into esbuild, maybe this provides a solution to my problem, but it would be really nice if this library could be used to use dynamic imports with deno compile

**Comment by danielr1996** [comment]
After further investigation I found the error comes from https://github.com/lucacasonato/esbuild_deno_loader/blob/70c34bb6d77b2dd05255f0e4a813bb62239d62d1/src/deno.ts#L48, as it seems `esbuild_deno_loader` uses `Deno.execPath` which should return the path to the deno executable if run as `deno run`, but returns the path to the compiled binary when compiled with `deno compile`. So I will try to patch `esbuild_deno_loader` and see if it works then. So I think there is nothing in this libary for now that can be done to support my usecase. I will report back if I have more info

**Comment by danielr1996** [comment]
Yep it was only the call to deno info which causes the error. So I've created a pull request in esbuild_deno_loader and if that gets merged we could include it here.

**Comment by ayoreis** [comment]
Yes! Having this working with `deno compile` would be a nice feature, there're some other more significant issues I want to fix first (trying to get them done today). After that, I'll be happy to fix/merge this.

BTW this's my first issue!

**Comment by ayoreis** [comment]
Hi @danielr1996. I'm ok with just changing the `loader` to `'portable'` to fix this, but can you first update your fork to resolve conflicts?

About what you said in the PR about relative imports, I implemented that here, you can check the code. Basically, it creates a new `Error` and checks its `stack` property.

**Comment by danielr1996** [comment]
Hi @ayoreis, sorry for the late answer, I didn't work on my project for a while now. I tried tp update my pr but now I get weird deno panic errors, when I figured them out I will post a new PR

**Comment by ayoreis** [comment]
Thanks a lot for your help! I'm going to change the `loader` to `portable` and release this today.
