### ISSUE TITLE
Module source is being botched by mod.ts:95-101

### ISSUE THREAD

**Issue by gnestor** [ayoreis/import#10]
I'm trying to work around the dynamic import issue with Deno Deploy (https://github.com/denoland/deploy_feedback/issues/1) and I'm getting the following error when using `importModule` vs. native `import`:

```
SyntaxError: Unexpected token 'default'
    at AsyncFunction (<anonymous>)
    at buildAndEvaluate (https://deno.land/x/import@v0.1.6/mod.ts:58:12)
    at async importModule (https://deno.land/x/import@v0.1.6/mod.ts:70:16)
    at async getNotebook (file:///src/observable.ts:30:31)
```

I'm trying to dynamically import Observable notebooks. It works fine when running the Deno script locally and using native `import`. 

Here's an example: https://api.observablehq.com/d/6388e91a5ea79803.js?v=3

The source is importing with native import or when you fetch this is:

```js
function _1(md){return(
md`# Deno Function Test`
)}

function _addTwo(){return(
x => x + 2
)}

function _result(addTwo){return(
addTwo(2)
)}

export default function define(runtime, observer) {
  const main = runtime.module();
  main.variable(observer()).define(["md"], _1);
  main.variable(observer("addTwo")).define("addTwo", _addTwo);
  main.variable(observer("result")).define("result", ["addTwo"], _result);
  return main;
}
```

However, what I'm seeing for `body` at [`AsyncFunction` (mod.ts:103)](https://github.com/ayoreis/import/blob/main/mod.ts#L103) is:

```js
// deno:https://api.observablehq.com/d/6388e91a5ea79803.js?v=3&api_key=a9cb22008fc47c23b8bc2d0dc269949b1d1aaeee&cache=1670648818850
function _1(md) {
  return md`# Deno Function Test`;
}
function _addTwo() {
  return (x) => x + 2;
}
function _result(addTwo) {
  return addTwo(2);
}
function define(runtime, observer) {
  const main = runtime.module();
  main.variable(observer()).define(["md"], _1);
  main.variable(observer("addTwo")).define("addTwo", _addTwo);
  main.variable(observer("result")).define("result", ["addTwo"], _result);
  return main;
}
return {default
};
: 
  define
```

It appears that this is the culprit: https://github.com/ayoreis/import/blob/main/mod.ts#L95-L101

**Comment by gnestor** [comment]
I was able to fix this for my use case by replacing:

```js
const { text = '' } = buildResult.outputFiles?.[0] ?? {}
const [before, after = '}'] = text.split('export {')
const body =
	stripShebang(before).replaceAll('import.meta', '{}') +
	'return {' +
	after.replaceAll(
		/(?<local>[\w\W]+) as (?<exported>[\w\W]+)/g,
		'$<exported>: $<local>',
	)
```

with:

```js
const body = text.replace(
  /export {\n.*(define.*) as default.*\n.*}/gm,
  'return { default: $1 }'
);
```

I'm not sure if this is a generic solution since Observable notebooks, when processed with esbuild, also end with a:

```js
export {
   define{ID} as default
}
```

**Comment by ayoreis** [comment]
Thank you for the issue, I think I've fixed it in the latest release (removed the `\W` from that RegEx). I tested it on that link you shared and all worked great, but could you check to ensure it works?

**Comment by gnestor** [comment]
It's working! Thanks 👍
