### ISSUE TITLE
Using `importModule` inside `importString`

### ISSUE THREAD

**Issue by vfssantos** [ayoreis/import#15]
I have a use case where I need to import other modules from a JS string:

```javascript
import { importString, importModule } from "https://deno.land/x/import/mod.ts";

let code = `
const renderer = async ()=>{
    const { render } = await importModule('https://deno.land/x/mustache_ts/mustache.ts');
    console.log(render)
    const template = '{{title}} spends {{calc}}'
    const view = {
        title: 'Joe',
        calc: () => 2 + 4
    }
    const output = render(template, view)
    return output
}
export default renderer
`

const {default:renderer} = await importString(code);
renderer().then(console.log) // expected: "Joe spends 6
```

Possible solution: passing an object of "dependencies" to the "importString" function as a second parameter, in which we could use the `importModule` or even other custom modules as well.

**Comment by vfssantos** [comment]
Proposed solution implemented in #17 

I'd be happy to make any revisions to the code if necessary.

**Comment by ayoreis** [comment]
Looks good to me.

I would recommend to reimport `importModule` from within the string if wouldn't add more modules to be built by esbuild which in turn will make it take longer. So This feels like the right workaround for me.

Can I merge?

**Comment by vfssantos** [comment]
Great, thanks. I've been using it in Deno Deploy already, and it's working fine. So I'd say we're good to go with the merge. 😀
